CREATE TABLE "ads" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"user_id" uuid NOT NULL,
	"images" text[],
	"phone_number" text DEFAULT '000000000' NOT NULL,
	"phone_country_code" text DEFAULT '000',
	"city" text DEFAULT '-' NOT NULL,
	"country" text DEFAULT '-' NOT NULL,
	"district" text DEFAULT '-' NOT NULL,
	"address" text DEFAULT '-' NOT NULL,
	"municipalityLicense" boolean DEFAULT false,
	"civilDefenseLicense" boolean,
	"SFDAFoodLicense" boolean DEFAULT false,
	"SFDACosmeticsLicense" boolean DEFAULT false,
	"SFDAMedicalEquipmentLicense" boolean DEFAULT false,
	"SFDAPharmaLicense" boolean DEFAULT false,
	"SFDAPetFoodLicense" boolean DEFAULT false,
	"SFDAPesticidesLicense" boolean DEFAULT false,
	"price" text DEFAULT '0' NOT NULL,
	"payment_term" text DEFAULT 'monthly',
	"available_date_from" date,
	"available_date_to" date,
	"type" text,
	"temperature_settings" text,
	"hazard_level" text,
	"flooring" text,
	"forklift_availability" text,
	"racking_system" text,
	"number_of_streets" text,
	"number_of_doors" text,
	"number_of_walls" text,
	"area_in_m2" text,
	"security_cameras" boolean,
	"manual_ramp" boolean,
	"automatic_ramp" boolean,
	"published" boolean DEFAULT true NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"verified" boolean DEFAULT false NOT NULL,
	"lat" double precision,
	"lng" double precision,
	"meeting_url" text,
	"date_added" text,
	"facade" text,
	"has_electricity" boolean,
	"has_sewage" boolean,
	"has_water" boolean,
	"last_updated" text,
	"length" text,
	"property_age" text,
	"scraped_id" text,
	"street_width" text,
	"width" text,
	"for_rent" boolean DEFAULT true,
	"for_sale" boolean DEFAULT false,
	"for_daily_rent" boolean DEFAULT false,
	"type_attributes" jsonb
);
--> statement-breakpoint
CREATE TABLE "blog_posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"slug" text NOT NULL,
	"author" text DEFAULT 'Sirdab',
	"published_at" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bookings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" text NOT NULL,
	"user_id" uuid,
	"customer_name" text NOT NULL,
	"customer_email" text NOT NULL,
	"customer_phone" text NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"total_price" bigint NOT NULL,
	"platform_fee" bigint NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"payment_status" text DEFAULT 'unpaid' NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name_en" text NOT NULL,
	"name_ar" text NOT NULL,
	"slug" text NOT NULL,
	"region" text,
	"is_active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "saved_properties" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"property_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text,
	"email" text,
	"email_verified" timestamp with time zone,
	"image" text,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"stripe_price_id" text,
	"stripe_current_period_end" timestamp with time zone,
	"meeting_url" text
);
--> statement-breakpoint
CREATE TABLE "visits" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" text NOT NULL,
	"user_id" uuid,
	"visitor_name" text NOT NULL,
	"visitor_email" text NOT NULL,
	"visitor_phone" text NOT NULL,
	"visit_date" text NOT NULL,
	"visit_time" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"notes" text
);
